# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolkit < Formula
  desc "Toolkit CLI: cross-platform command-line tool for cloud & infra automation"
  homepage "https://github.com/jingle2008/toolkit"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.1.2/toolkit_0.1.2_darwin_amd64.tar.gz"
      sha256 "29772807d7602fb6ea1eeb37bbae52d0263dbd886d786857790a4dcc07da0bc3"

      def install
        bin.install "toolkit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.1.2/toolkit_0.1.2_darwin_arm64.tar.gz"
      sha256 "0e161b5c6766677e56132e29b5c3449f14ed716ea1264e1bd5f32f86bbc98194"

      def install
        bin.install "toolkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.1.2/toolkit_0.1.2_linux_amd64.tar.gz"
      sha256 "043a31e557de5b87b092900ead4f694dc6d57da4a98f8c6a9682556af4586d2d"
      def install
        bin.install "toolkit"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.1.2/toolkit_0.1.2_linux_arm64.tar.gz"
      sha256 "432926e30b6058fe9aeb5a4079d062cad89eeb5c9bc136fbede5690a805776d2"
      def install
        bin.install "toolkit"
      end
    end
  end

  test do
    system "#{bin}/toolkit", "--version"
  end
end
