# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolkit" do
  desc "Toolkit CLI: cross-platform command-line tool for cloud and infrastructure automation"
  homepage "https://github.com/jingle2008/toolkit"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolkit"

  on_macos do
    on_intel do
      url "https://github.com/jingle2008/toolkit/releases/download/v0.1.1/toolkit_0.1.1_darwin_amd64.tar.gz"
      sha256 "cd3c67d959f4a135162a38be19ecec6ed6b5fe3a0373056186509503d4df79de"
    end
    on_arm do
      url "https://github.com/jingle2008/toolkit/releases/download/v0.1.1/toolkit_0.1.1_darwin_arm64.tar.gz"
      sha256 "6320c41a6def6ff19e90da14df64ac5cfa4d744074e1b8f3eefe0906603b9034"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jingle2008/toolkit/releases/download/v0.1.1/toolkit_0.1.1_linux_amd64.tar.gz"
      sha256 "1f3ff570afdf17672943638e0bd24179a26db2f25412a8d2871394089342db09"
    end
    on_arm do
      url "https://github.com/jingle2008/toolkit/releases/download/v0.1.1/toolkit_0.1.1_linux_arm64.tar.gz"
      sha256 "c732a793925c38eba132d92ad04917cf2ed89e53b4bac69a9211f10b7e2f82cc"
    end
  end

  # No zap stanza required
end
