# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolkit" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "2bea810e6229c3844bc6eecbf554143e35f605e2304b4293f32a83ae552a3236"
      url "https://github.com/jingle2008/toolkit/releases/download/v#{version}/toolkit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bb19745e8a0b5ab44ab1f6d920a2366aa50e59a5dcf2514aa67b28b75defd3ca"
      url "https://github.com/jingle2008/toolkit/releases/download/v#{version}/toolkit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "292c0952f708802bb261ef9c38fd23da8782eb6cd56ad7609e9245a93bc901b1"
      url "https://github.com/jingle2008/toolkit/releases/download/v#{version}/toolkit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5bb7dddf5b28d5d26490f3bd6226272ee54e895070c44264de69faf94e614077"
      url "https://github.com/jingle2008/toolkit/releases/download/v#{version}/toolkit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "toolkit"
  desc "Toolkit CLI: cross-platform command-line tool for cloud and infrastructure automation"
  homepage "https://github.com/jingle2008/toolkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolkit"

  # No zap stanza required

end
