# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolkit" do
  desc "Toolkit CLI: cross-platform command-line tool for cloud and infrastructure automation"
  homepage "https://github.com/jingle2008/toolkit"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolkit"

  on_macos do
    on_intel do
      url "https://github.com/jingle2008/toolkit/releases/download/v0.1.3/toolkit_0.1.3_darwin_amd64.tar.gz"
      sha256 "f2cae7a3709a8f3744ac61f2d144f546eff2a9bc7143972ad975fe1ce3f2b157"
    end
    on_arm do
      url "https://github.com/jingle2008/toolkit/releases/download/v0.1.3/toolkit_0.1.3_darwin_arm64.tar.gz"
      sha256 "18c09cb8285eaec5ae5e57d3eb08683d4057d1a0b95b20d186655b4c1cb1703a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jingle2008/toolkit/releases/download/v0.1.3/toolkit_0.1.3_linux_amd64.tar.gz"
      sha256 "f2463e01e131a080125da354511a6e50d58020de29707b5cdfb87544ef10a0cc"
    end
    on_arm do
      url "https://github.com/jingle2008/toolkit/releases/download/v0.1.3/toolkit_0.1.3_linux_arm64.tar.gz"
      sha256 "107f24fbf1f859bcfcc6f6689dd56e53505672e6f7e64f7e4ec1d24f80720503"
    end
  end

  # No zap stanza required
end
