# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolkit < Formula
  desc "Toolkit CLI: cross-platform command-line tool for cloud & infra automation"
  homepage "https://github.com/jingle2008/toolkit"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.2.0/toolkit_0.2.0_darwin_amd64.tar.gz"
      sha256 "73590ffe6cffcae9b8cb50b90bf68c69bdf76d960347b749b34cb7259af75763"

      define_method(:install) do
        bin.install "toolkit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.2.0/toolkit_0.2.0_darwin_arm64.tar.gz"
      sha256 "1c06adbc2c6d530904aa8cc3ffcea9d9619090732ceac6396ed064d7b47ebb4e"

      define_method(:install) do
        bin.install "toolkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.2.0/toolkit_0.2.0_linux_amd64.tar.gz"
      sha256 "14bfb548e875894f1f3b4e7c2c2a1262b95b11b939838d8074c1db27e748b20d"
      define_method(:install) do
        bin.install "toolkit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.2.0/toolkit_0.2.0_linux_arm64.tar.gz"
      sha256 "533fc029dde131a7357e0d910440240ae6f02757ab62a5fbba3e0bd0a77d2381"
      define_method(:install) do
        bin.install "toolkit"
      end
    end
  end

  test do
    system "#{bin}/toolkit", "--version"
  end
end
