# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolkit < Formula
  desc "Toolkit CLI: cross-platform command-line tool for cloud & infra automation"
  homepage "https://github.com/jingle2008/toolkit"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.1.4/toolkit_0.1.4_darwin_amd64.tar.gz"
      sha256 "469871b7cac78234c5a005a085748e14cd6dda37c88fb3a59b65526b932b165b"

      def install
        bin.install "toolkit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.1.4/toolkit_0.1.4_darwin_arm64.tar.gz"
      sha256 "4e94caad34564bfe374cdfdc4f7fcd4332d7c2397b920da569738c4920a742f1"

      def install
        bin.install "toolkit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.1.4/toolkit_0.1.4_linux_amd64.tar.gz"
      sha256 "abe242864076dd3b12d9dfa5bccbb4e654d302c78a666f8df944457007365fad"
      def install
        bin.install "toolkit"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jingle2008/toolkit/releases/download/v0.1.4/toolkit_0.1.4_linux_arm64.tar.gz"
      sha256 "ebe2622a6246f16727d7713ab6b9878a3814b971991030b36b1aaf1c1964ffb7"
      def install
        bin.install "toolkit"
      end
    end
  end

  test do
    system "#{bin}/toolkit", "--version"
  end
end
